name: "Project Template Action"
description: "GitHub action to create Project Boards from template Yaml files"

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true

runs:
  using: node14
  main: index.js
