---
projects:
  - name: Project_3
    description: Test Project 1 
    # Milestone due date - example format '2022-11-10T00:00:00Z'
    duedate: '2022-11-10T00:00:00Z'
    columns:

      - name: ToDo
        manage: none
        cards:
          - name: Issue_1
            type: Issue
            template: task
            parameters:
              TASK: BUG
              TITLE: another one
          - name: Issue_2
            type: Issue
            template: task
            parameters:
              TASK: RFC
              TITLE: new request
          - name: Issue_3
            type: Card
            template: task
            parameters:
              TASK: RFC
              TITLE: new request

      - name: InProgress
        manage: none
        cards:
          - name: Issue_4
            type: Issue
            template: bug
            parameters:
              TASK: BUG
              TITLE: new bug

      - name: Review
        manage: none

      - name: Done
        manage: none
