---
projects:
  - name: Project_3
    description: Test Project 1 
    columns:

      - name: ToDo
        manage: none
        cards:
          - name: Issue_1
            type: Issue
            template: task
            parameters:
              TASK: BUG
              TITLE: another one
          - name: Issue_2
            type: Issue
            template: task
            parameters:
              TASK: RFC
              TITLE: new request
          - name: Issue_3
            type: Card
            template: task
            parameters:
              TASK: RFC
              TITLE: new request

      - name: InProgress
        manage: none

      - name: Done
        manage: none
