name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install @octokit/action
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_PAT }}
      - uses: ./
