name: Test

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: template
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install @octokit/action
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          templateName: migration-project-template.yml
